<?xml version="1.0"?>
<package format="3">
  <name>drone_description</name>
  <version>0.1.0</version>
  <description>SDF model containing only the course physical parameters and sensors.</description>
  <maintainer email="maintainer@example.com">MA6224 team</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
